version: '3.3'
services:
  backend:
    build: ./backend
    container_name: ${BACKEND_CONTAINER_NAME}
    expose:
      - '5000'
    restart: on-failure
    ports:
      - ${BACKEND_PORT}:5000
    volumes:
      - ./.env:/usr/src/app/.env
  mongo: 
    image: mongo
    container_name: ${MONGO_CONTAINER_NAME}
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:
